version: "3.5"
services:
  mqtt-respeaker-pixel-ring:
    image: jacopomaroli/mqtt_respeaker_pixel_ring:master
    container_name: mqtt-respeaker-pixel-ring
    env_file:
      - .env
    environment:
      - TZ="Europe/London"
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
